export type PartOfSpeech =
  | "verb"
  | "noun"
  | "adjective"
  | "adverb"
  | "pronoun"
  | "numeral"
  | "classifier"
  | "particle"
  | "conjunction"
  | "preposition"
  | "interjection"
  | "prefix"
  | "suffix"
  | "fixed expression"
  | "verb phrase"
  | "quantifier"
  | "other";

export interface Word {
  id: number;
  hanzi: string;
  pinyin: string;
  meaning: string;
  partOfSpeech: PartOfSpeech;
  exampleHanzi: string;
  examplePinyin: string;
  exampleMeaning: string;
}

export const words: Word[] = [
  { id: 1, hanzi: "爱", pinyin: "ài", meaning: "to love", partOfSpeech: "verb", exampleHanzi: "我爱你。", examplePinyin: "Wǒ ài nǐ.", exampleMeaning: "I love you." },
  { id: 2, hanzi: "吧", pinyin: "ba", meaning: "used to make suggestions", partOfSpeech: "particle", exampleHanzi: "我们走吧。", examplePinyin: "Wǒmen zǒu ba.", exampleMeaning: "Let's go." },
  { id: 3, hanzi: "八", pinyin: "bā", meaning: "eight", partOfSpeech: "numeral", exampleHanzi: "我有八个学生。", examplePinyin: "Wǒ yǒu bā gè xuéshēng.", exampleMeaning: "I have eight students." },
  { id: 4, hanzi: "爸爸", pinyin: "bàba", meaning: "dad / father", partOfSpeech: "noun", exampleHanzi: "我爸爸在家。", examplePinyin: "Wǒ bàba zài jiā.", exampleMeaning: "My dad is at home." },
  { id: 5, hanzi: "百", pinyin: "bǎi", meaning: "hundred", partOfSpeech: "numeral", exampleHanzi: "这本书一百元。", examplePinyin: "Zhè běn shū yì bǎi yuán.", exampleMeaning: "This book costs one hundred yuan." },
  { id: 6, hanzi: "白天", pinyin: "báitiān", meaning: "daytime", partOfSpeech: "noun", exampleHanzi: "白天我上班。", examplePinyin: "Báitiān wǒ shàngbān.", exampleMeaning: "I work during the daytime." },
  { id: 7, hanzi: "半", pinyin: "bàn", meaning: "half", partOfSpeech: "numeral", exampleHanzi: "我吃一半。", examplePinyin: "Wǒ chī yí bàn.", exampleMeaning: "I eat half." },
  { id: 8, hanzi: "包子", pinyin: "bāozi", meaning: "steamed bun", partOfSpeech: "noun", exampleHanzi: "我吃包子。", examplePinyin: "Wǒ chī bāozi.", exampleMeaning: "I eat steamed buns." },
  { id: 9, hanzi: "杯子", pinyin: "bēizi", meaning: "cup", partOfSpeech: "noun", exampleHanzi: "这是我的杯子。", examplePinyin: "Zhè shì wǒ de bēizi.", exampleMeaning: "This is my cup." },
  { id: 10, hanzi: "本", pinyin: "běn", meaning: "measure word for books", partOfSpeech: "classifier", exampleHanzi: "我有一本书。", examplePinyin: "Wǒ yǒu yì běn shū.", exampleMeaning: "I have one book." },
  { id: 11, hanzi: "边", pinyin: "biān", meaning: "side", partOfSpeech: "noun", exampleHanzi: "他在我边上。", examplePinyin: "Tā zài wǒ biān shàng.", exampleMeaning: "He is next to me." },
  { id: 12, hanzi: "病", pinyin: "bìng", meaning: "illness; to be ill", partOfSpeech: "noun", exampleHanzi: "他病了。", examplePinyin: "Tā bìng le.", exampleMeaning: "He is sick." },
  { id: 13, hanzi: "不", pinyin: "bù", meaning: "not", partOfSpeech: "adverb", exampleHanzi: "我不去学校。", examplePinyin: "Wǒ bù qù xuéxiào.", exampleMeaning: "I'm not going to school." },
  { id: 14, hanzi: "不客气", pinyin: "bú kèqi", meaning: "you're welcome", partOfSpeech: "fixed expression", exampleHanzi: "谢谢你。不客气。", examplePinyin: "Xièxie nǐ. Bú kèqi.", exampleMeaning: "Thank you. You're welcome." },
  { id: 15, hanzi: "不要", pinyin: "bú yào", meaning: "don't", partOfSpeech: "adverb", exampleHanzi: "不要说话。", examplePinyin: "Bú yào shuōhuà.", exampleMeaning: "Don't talk." },
  { id: 16, hanzi: "菜", pinyin: "cài", meaning: "dish / vegetables", partOfSpeech: "noun", exampleHanzi: "这个菜很好吃。", examplePinyin: "Zhège cài hěn hǎochī.", exampleMeaning: "This dish is very delicious." },
  { id: 17, hanzi: "茶", pinyin: "chá", meaning: "tea", partOfSpeech: "noun", exampleHanzi: "我喝茶。", examplePinyin: "Wǒ hē chá.", exampleMeaning: "I drink tea." },
  { id: 18, hanzi: "唱", pinyin: "chàng", meaning: "to sing", partOfSpeech: "verb", exampleHanzi: "她唱歌。", examplePinyin: "Tā chàng gē.", exampleMeaning: "She sings." },
  { id: 19, hanzi: "超市", pinyin: "chāoshì", meaning: "supermarket", partOfSpeech: "noun", exampleHanzi: "我去超市买东西。", examplePinyin: "Wǒ qù chāoshì mǎi dōngxi.", exampleMeaning: "I go to the supermarket to buy things." },
  { id: 20, hanzi: "车", pinyin: "chē", meaning: "vehicle", partOfSpeech: "noun", exampleHanzi: "这是我的车。", examplePinyin: "Zhè shì wǒ de chē.", exampleMeaning: "This is my car." },
  { id: 21, hanzi: "吃", pinyin: "chī", meaning: "to eat", partOfSpeech: "verb", exampleHanzi: "我吃饭。", examplePinyin: "Wǒ chī fàn.", exampleMeaning: "I eat a meal." },
  { id: 22, hanzi: "穿", pinyin: "chuān", meaning: "to wear", partOfSpeech: "verb", exampleHanzi: "他穿衣服。", examplePinyin: "Tā chuān yīfu.", exampleMeaning: "He wears clothes." },
  { id: 23, hanzi: "出租车", pinyin: "chūzūchē", meaning: "taxi", partOfSpeech: "noun", exampleHanzi: "我坐出租车。", examplePinyin: "Wǒ zuò chūzūchē.", exampleMeaning: "I take a taxi." },
  { id: 24, hanzi: "大", pinyin: "dà", meaning: "big", partOfSpeech: "adjective", exampleHanzi: "这个房间很大。", examplePinyin: "Zhège fángjiān hěn dà.", exampleMeaning: "This room is big." },
  { id: 25, hanzi: "打电话", pinyin: "dǎ diànhuà", meaning: "to make a phone call", partOfSpeech: "fixed expression", exampleHanzi: "我给妈妈打电话。", examplePinyin: "Wǒ gěi māma dǎ diànhuà.", exampleMeaning: "I call my mom." },
  { id: 26, hanzi: "大家", pinyin: "dàjiā", meaning: "everyone", partOfSpeech: "pronoun", exampleHanzi: "大家好。", examplePinyin: "Dàjiā hǎo.", exampleMeaning: "Hello, everyone." },
  { id: 27, hanzi: "到", pinyin: "dào", meaning: "to arrive", partOfSpeech: "verb", exampleHanzi: "我到学校了。", examplePinyin: "Wǒ dào xuéxiào le.", exampleMeaning: "I arrived at school." },
  { id: 28, hanzi: "大学", pinyin: "dàxué", meaning: "university", partOfSpeech: "noun", exampleHanzi: "他在大学学习。", examplePinyin: "Tā zài dàxué xuéxí.", exampleMeaning: "He studies at a university." },
  { id: 29, hanzi: "大学生", pinyin: "dàxuéshēng", meaning: "university student", partOfSpeech: "noun", exampleHanzi: "她是大学生。", examplePinyin: "Tā shì dàxuéshēng.", exampleMeaning: "She is a university student." },
  { id: 30, hanzi: "的", pinyin: "de", meaning: "shows possession", partOfSpeech: "particle", exampleHanzi: "这是我的书。", examplePinyin: "Zhè shì wǒ de shū.", exampleMeaning: "This is my book." },
  { id: 31, hanzi: "第", pinyin: "dì", meaning: "ordinal marker", partOfSpeech: "prefix", exampleHanzi: "这是第一课。", examplePinyin: "Zhè shì dì yī kè.", exampleMeaning: "This is the first lesson." },
  { id: 32, hanzi: "店", pinyin: "diàn", meaning: "shop", partOfSpeech: "noun", exampleHanzi: "这家店很大。", examplePinyin: "Zhè jiā diàn hěn dà.", exampleMeaning: "This shop is big." },
  { id: 33, hanzi: "点", pinyin: "diǎn", meaning: "o'clock", partOfSpeech: "classifier", exampleHanzi: "现在三点。", examplePinyin: "Xiànzài sān diǎn.", exampleMeaning: "It's three o'clock now." },
  { id: 34, hanzi: "电话", pinyin: "diànhuà", meaning: "telephone", partOfSpeech: "noun", exampleHanzi: "我的电话在这儿。", examplePinyin: "Wǒ de diànhuà zài zhèr.", exampleMeaning: "My phone is here." },
  { id: 35, hanzi: "电脑", pinyin: "diànnǎo", meaning: "computer", partOfSpeech: "noun", exampleHanzi: "我有一台电脑。", examplePinyin: "Wǒ yǒu yì tái diànnǎo.", exampleMeaning: "I have a computer." },
  { id: 36, hanzi: "电视", pinyin: "diànshì", meaning: "television", partOfSpeech: "noun", exampleHanzi: "我们看电视。", examplePinyin: "Wǒmen kàn diànshì.", exampleMeaning: "We watch TV." },
  { id: 37, hanzi: "电影", pinyin: "diànyǐng", meaning: "movie", partOfSpeech: "noun", exampleHanzi: "我看电影。", examplePinyin: "Wǒ kàn diànyǐng.", exampleMeaning: "I watch a movie." },
  { id: 38, hanzi: "电影院", pinyin: "diànyǐngyuàn", meaning: "cinema", partOfSpeech: "noun", exampleHanzi: "我们去电影院。", examplePinyin: "Wǒmen qù diànyǐngyuàn.", exampleMeaning: "We go to the cinema." },
  { id: 39, hanzi: "弟弟", pinyin: "dìdi", meaning: "younger brother", partOfSpeech: "noun", exampleHanzi: "我弟弟在家。", examplePinyin: "Wǒ dìdi zài jiā.", exampleMeaning: "My younger brother is at home." },
  { id: 40, hanzi: "东西", pinyin: "dōngxi", meaning: "thing", partOfSpeech: "noun", exampleHanzi: "我买了东西。", examplePinyin: "Wǒ mǎi le dōngxi.", exampleMeaning: "I bought some things." },
  { id: 41, hanzi: "都", pinyin: "dōu", meaning: "all", partOfSpeech: "adverb", exampleHanzi: "我们都是学生。", examplePinyin: "Wǒmen dōu shì xuéshēng.", exampleMeaning: "We are all students." },
  { id: 42, hanzi: "读", pinyin: "dú", meaning: "to read", partOfSpeech: "verb", exampleHanzi: "我读书。", examplePinyin: "Wǒ dú shū.", exampleMeaning: "I read books." },
  { id: 43, hanzi: "对", pinyin: "duì", meaning: "correct", partOfSpeech: "adjective", exampleHanzi: "你说得对。", examplePinyin: "Nǐ shuō de duì.", exampleMeaning: "You're right." },
  { id: 44, hanzi: "对不起", pinyin: "duìbuqǐ", meaning: "sorry", partOfSpeech: "fixed expression", exampleHanzi: "对不起。", examplePinyin: "Duìbuqǐ.", exampleMeaning: "I'm sorry." },
  { id: 45, hanzi: "多", pinyin: "duō", meaning: "many / much", partOfSpeech: "adjective", exampleHanzi: "人很多。", examplePinyin: "Rén hěn duō.", exampleMeaning: "There are many people." },
  { id: 46, hanzi: "多少", pinyin: "duōshao", meaning: "how many / how much", partOfSpeech: "pronoun", exampleHanzi: "你要多少？", examplePinyin: "Nǐ yào duōshao?", exampleMeaning: "How many do you want?" },
  { id: 47, hanzi: "读书", pinyin: "dúshū", meaning: "to study", partOfSpeech: "verb", exampleHanzi: "我在读书。", examplePinyin: "Wǒ zài dúshū.", exampleMeaning: "I am studying." },
  { id: 48, hanzi: "二", pinyin: "èr", meaning: "two", partOfSpeech: "numeral", exampleHanzi: "我有二本书。", examplePinyin: "Wǒ yǒu èr běn shū.", exampleMeaning: "I have two books." },
  { id: 49, hanzi: "儿子", pinyin: "érzi", meaning: "son", partOfSpeech: "noun", exampleHanzi: "他有一个儿子。", examplePinyin: "Tā yǒu yí gè érzi.", exampleMeaning: "He has a son." },
  { id: 50, hanzi: "饭", pinyin: "fàn", meaning: "meal", partOfSpeech: "noun", exampleHanzi: "我吃饭。", examplePinyin: "Wǒ chī fàn.", exampleMeaning: "I eat a meal." },
  { id: 51, hanzi: "饭店", pinyin: "fàndiàn", meaning: "restaurant", partOfSpeech: "noun", exampleHanzi: "我们去饭店吃饭。", examplePinyin: "Wǒmen qù fàndiàn chī fàn.", exampleMeaning: "We go to a restaurant to eat." },
  { id: 52, hanzi: "房间", pinyin: "fángjiān", meaning: "room", partOfSpeech: "noun", exampleHanzi: "这个房间很小。", examplePinyin: "Zhège fángjiān hěn xiǎo.", exampleMeaning: "This room is small." },
  { id: 53, hanzi: "非常", pinyin: "fēicháng", meaning: "very", partOfSpeech: "adverb", exampleHanzi: "我非常高兴。", examplePinyin: "Wǒ fēicháng gāoxìng.", exampleMeaning: "I'm very happy." },
  { id: 54, hanzi: "飞机", pinyin: "fēijī", meaning: "airplane", partOfSpeech: "noun", exampleHanzi: "我坐飞机。", examplePinyin: "Wǒ zuò fēijī.", exampleMeaning: "I take a plane." },
  { id: 55, hanzi: "分", pinyin: "fēn", meaning: "minute", partOfSpeech: "classifier", exampleHanzi: "现在五分。", examplePinyin: "Xiànzài wǔ fēn.", exampleMeaning: "It's five minutes past." },
  { id: 56, hanzi: "分钟", pinyin: "fēnzhōng", meaning: "minute", partOfSpeech: "classifier", exampleHanzi: "十分钟以后。", examplePinyin: "Shí fēnzhōng yǐhòu.", exampleMeaning: "After ten minutes." },
  { id: 57, hanzi: "高兴", pinyin: "gāoxìng", meaning: "happy", partOfSpeech: "adjective", exampleHanzi: "我很高兴。", examplePinyin: "Wǒ hěn gāoxìng.", exampleMeaning: "I'm happy." },
  { id: 58, hanzi: "个", pinyin: "gè", meaning: "general measure word", partOfSpeech: "classifier", exampleHanzi: "一个人。", examplePinyin: "Yí gè rén.", exampleMeaning: "One person." },
  { id: 59, hanzi: "歌", pinyin: "gē", meaning: "song", partOfSpeech: "noun", exampleHanzi: "我听歌。", examplePinyin: "Wǒ tīng gē.", exampleMeaning: "I listen to songs." },
  { id: 60, hanzi: "哥哥", pinyin: "gēge", meaning: "older brother", partOfSpeech: "noun", exampleHanzi: "我哥哥工作。", examplePinyin: "Wǒ gēge gōngzuò.", exampleMeaning: "My older brother works." },
  { id: 61, hanzi: "给", pinyin: "gěi", meaning: "to give", partOfSpeech: "verb", exampleHanzi: "我给你书。", examplePinyin: "Wǒ gěi nǐ shū.", exampleMeaning: "I give you a book." },
  { id: 62, hanzi: "公司", pinyin: "gōngsī", meaning: "company", partOfSpeech: "noun", exampleHanzi: "他在公司工作。", examplePinyin: "Tā zài gōngsī gōngzuò.", exampleMeaning: "He works at a company." },
  { id: 63, hanzi: "工作", pinyin: "gōngzuò", meaning: "to work; work", partOfSpeech: "verb", exampleHanzi: "我在工作。", examplePinyin: "Wǒ zài gōngzuò.", exampleMeaning: "I am working." },
  { id: 64, hanzi: "狗", pinyin: "gǒu", meaning: "dog", partOfSpeech: "noun", exampleHanzi: "我有一只狗。", examplePinyin: "Wǒ yǒu yì zhī gǒu.", exampleMeaning: "I have a dog." },
  { id: 65, hanzi: "贵", pinyin: "guì", meaning: "expensive", partOfSpeech: "adjective", exampleHanzi: "这个很贵。", examplePinyin: "Zhège hěn guì.", exampleMeaning: "This is expensive." },
  { id: 66, hanzi: "国", pinyin: "guó", meaning: "country", partOfSpeech: "noun", exampleHanzi: "中国是一个大国。", examplePinyin: "Zhōngguó shì yí gè dà guó.", exampleMeaning: "China is a big country." },
  { id: 67, hanzi: "还", pinyin: "hái", meaning: "still", partOfSpeech: "adverb", exampleHanzi: "我还在家。", examplePinyin: "Wǒ hái zài jiā.", exampleMeaning: "I am still at home." },
  { id: 68, hanzi: "孩子", pinyin: "háizi", meaning: "child", partOfSpeech: "noun", exampleHanzi: "这个孩子很高兴。", examplePinyin: "Zhège háizi hěn gāoxìng.", exampleMeaning: "This child is happy." },
  { id: 69, hanzi: "汉语", pinyin: "Hànyǔ", meaning: "Chinese language", partOfSpeech: "noun", exampleHanzi: "我学汉语。", examplePinyin: "Wǒ xué Hànyǔ.", exampleMeaning: "I study Chinese." },
  { id: 70, hanzi: "汉字", pinyin: "Hànzì", meaning: "Chinese character", partOfSpeech: "noun", exampleHanzi: "我写汉字。", examplePinyin: "Wǒ xiě Hànzì.", exampleMeaning: "I write Chinese characters." },
  { id: 71, hanzi: "号", pinyin: "hào", meaning: "number; date", partOfSpeech: "classifier", exampleHanzi: "今天是三号。", examplePinyin: "Jīntiān shì sān hào.", exampleMeaning: "Today is the third." },
  { id: 72, hanzi: "好", pinyin: "hǎo", meaning: "good", partOfSpeech: "adjective", exampleHanzi: "这个很好。", examplePinyin: "Zhège hěn hǎo.", exampleMeaning: "This is good." },
  { id: 73, hanzi: "好吃", pinyin: "hǎochī", meaning: "delicious", partOfSpeech: "adjective", exampleHanzi: "这个菜很好吃。", examplePinyin: "Zhège cài hěn hǎochī.", exampleMeaning: "This dish is delicious." },
  { id: 74, hanzi: "好看", pinyin: "hǎokàn", meaning: "good-looking", partOfSpeech: "adjective", exampleHanzi: "这本书很好看。", examplePinyin: "Zhè běn shū hěn hǎokàn.", exampleMeaning: "This book looks good." },
  { id: 75, hanzi: "好听", pinyin: "hǎotīng", meaning: "pleasant to hear", partOfSpeech: "adjective", exampleHanzi: "这首歌很好听。", examplePinyin: "Zhè shǒu gē hěn hǎotīng.", exampleMeaning: "This song sounds nice." },
  { id: 76, hanzi: "好玩儿", pinyin: "hǎowánr", meaning: "fun", partOfSpeech: "adjective", exampleHanzi: "这个游戏很好玩儿。", examplePinyin: "Zhège yóuxì hěn hǎowánr.", exampleMeaning: "This game is fun." },
  { id: 77, hanzi: "和", pinyin: "hé", meaning: "and; with", partOfSpeech: "conjunction", exampleHanzi: "我和你去。", examplePinyin: "Wǒ hé nǐ qù.", exampleMeaning: "I go with you." },
  { id: 78, hanzi: "喝", pinyin: "hē", meaning: "to drink", partOfSpeech: "verb", exampleHanzi: "我喝水。", examplePinyin: "Wǒ hē shuǐ.", exampleMeaning: "I drink water." },
  { id: 79, hanzi: "很", pinyin: "hěn", meaning: "very", partOfSpeech: "adverb", exampleHanzi: "今天很冷。", examplePinyin: "Jīntiān hěn lěng.", exampleMeaning: "It is very cold today." },
  { id: 80, hanzi: "后", pinyin: "hòu", meaning: "after", partOfSpeech: "noun", exampleHanzi: "下课后。", examplePinyin: "Xiàkè hòu.", exampleMeaning: "After class." },
  { id: 81, hanzi: "回", pinyin: "huí", meaning: "to return", partOfSpeech: "verb", exampleHanzi: "我回家。", examplePinyin: "Wǒ huí jiā.", exampleMeaning: "I go home." },
  { id: 82, hanzi: "会", pinyin: "huì", meaning: "can; know how to", partOfSpeech: "verb", exampleHanzi: "我会说汉语。", examplePinyin: "Wǒ huì shuō Hànyǔ.", exampleMeaning: "I can speak Chinese." },
  { id: 83, hanzi: "火车", pinyin: "huǒchē", meaning: "train", partOfSpeech: "noun", exampleHanzi: "我坐火车。", examplePinyin: "Wǒ zuò huǒchē.", exampleMeaning: "I take the train." },
  { id: 84, hanzi: "几", pinyin: "jǐ", meaning: "how many", partOfSpeech: "pronoun", exampleHanzi: "你有几本书？", examplePinyin: "Nǐ yǒu jǐ běn shū?", exampleMeaning: "How many books do you have?" },
  { id: 85, hanzi: "家", pinyin: "jiā", meaning: "home; family", partOfSpeech: "noun", exampleHanzi: "我在家。", examplePinyin: "Wǒ zài jiā.", exampleMeaning: "I am at home." },
  { id: 86, hanzi: "见", pinyin: "jiàn", meaning: "to see", partOfSpeech: "verb", exampleHanzi: "我见老师。", examplePinyin: "Wǒ jiàn lǎoshī.", exampleMeaning: "I see the teacher." },
  { id: 87, hanzi: "件", pinyin: "jiàn", meaning: "measure word for clothes", partOfSpeech: "classifier", exampleHanzi: "一件衣服。", examplePinyin: "Yí jiàn yīfu.", exampleMeaning: "One piece of clothing." },
  { id: 88, hanzi: "叫", pinyin: "jiào", meaning: "to be called", partOfSpeech: "verb", exampleHanzi: "我叫李明。", examplePinyin: "Wǒ jiào Lǐ Míng.", exampleMeaning: "My name is Li Ming." },
  { id: 89, hanzi: "饺子", pinyin: "jiǎozi", meaning: "dumpling", partOfSpeech: "noun", exampleHanzi: "我吃饺子。", examplePinyin: "Wǒ chī jiǎozi.", exampleMeaning: "I eat dumplings." },
  { id: 90, hanzi: "家人", pinyin: "jiārén", meaning: "family member(s)", partOfSpeech: "noun", exampleHanzi: "我的家人在中国。", examplePinyin: "Wǒ de jiārén zài Zhōngguó.", exampleMeaning: "My family is in China." },
  { id: 91, hanzi: "鸡蛋", pinyin: "jīdàn", meaning: "egg", partOfSpeech: "noun", exampleHanzi: "我吃鸡蛋。", examplePinyin: "Wǒ chī jīdàn.", exampleMeaning: "I eat eggs." },
  { id: 92, hanzi: "姐姐", pinyin: "jiějie", meaning: "older sister", partOfSpeech: "noun", exampleHanzi: "我姐姐工作。", examplePinyin: "Wǒ jiějie gōngzuò.", exampleMeaning: "My older sister works." },
  { id: 93, hanzi: "今年", pinyin: "jīnnián", meaning: "this year", partOfSpeech: "noun", exampleHanzi: "今年我学汉语。", examplePinyin: "Jīnnián wǒ xué Hànyǔ.", exampleMeaning: "This year I study Chinese." },
  { id: 94, hanzi: "今天", pinyin: "jīntiān", meaning: "today", partOfSpeech: "noun", exampleHanzi: "今天星期五。", examplePinyin: "Jīntiān xīngqīwǔ.", exampleMeaning: "Today is Friday." },
  { id: 95, hanzi: "九", pinyin: "jiǔ", meaning: "nine", partOfSpeech: "numeral", exampleHanzi: "我有九个学生。", examplePinyin: "Wǒ yǒu jiǔ gè xuéshēng.", exampleMeaning: "I have nine students." },
  { id: 96, hanzi: "觉得", pinyin: "juéde", meaning: "to feel; to think", partOfSpeech: "verb", exampleHanzi: "我觉得很好。", examplePinyin: "Wǒ juéde hěn hǎo.", exampleMeaning: "I think it's very good." },
  { id: 97, hanzi: "开", pinyin: "kāi", meaning: "to open", partOfSpeech: "verb", exampleHanzi: "老师开门。", examplePinyin: "Lǎoshī kāi mén.", exampleMeaning: "The teacher opens the door." },
  { id: 98, hanzi: "开车", pinyin: "kāichē", meaning: "to drive", partOfSpeech: "verb", exampleHanzi: "他开车去公司。", examplePinyin: "Tā kāichē qù gōngsī.", exampleMeaning: "He drives to the company." },
  { id: 99, hanzi: "看", pinyin: "kàn", meaning: "to look; to watch", partOfSpeech: "verb", exampleHanzi: "我看书。", examplePinyin: "Wǒ kàn shū.", exampleMeaning: "I read a book." },
  { id: 100, hanzi: "看病", pinyin: "kànbìng", meaning: "to see a doctor", partOfSpeech: "verb", exampleHanzi: "他去看病。", examplePinyin: "Tā qù kànbìng.", exampleMeaning: "He goes to see a doctor." },
  { id: 101, hanzi: "看见", pinyin: "kànjiàn", meaning: "to see", partOfSpeech: "verb", exampleHanzi: "我看见老师了。", examplePinyin: "Wǒ kànjiàn lǎoshī le.", exampleMeaning: "I saw the teacher." },
  { id: 102, hanzi: "课", pinyin: "kè", meaning: "lesson", partOfSpeech: "noun", exampleHanzi: "今天有一节课。", examplePinyin: "Jīntiān yǒu yì jié kè.", exampleMeaning: "There is one class today." },
  { id: 103, hanzi: "可以", pinyin: "kěyǐ", meaning: "can; may", partOfSpeech: "verb", exampleHanzi: "我可以去。", examplePinyin: "Wǒ kěyǐ qù.", exampleMeaning: "I can go." },
  { id: 104, hanzi: "口", pinyin: "kǒu", meaning: "mouth", partOfSpeech: "classifier", exampleHanzi: "他有一口水。", examplePinyin: "Tā yǒu yì kǒu shuǐ.", exampleMeaning: "He has one sip of water." },
  { id: 105, hanzi: "块", pinyin: "kuài", meaning: "piece", partOfSpeech: "classifier", exampleHanzi: "一块蛋糕。", examplePinyin: "Yí kuài dàngāo.", exampleMeaning: "One piece of cake." },
  { id: 106, hanzi: "来", pinyin: "lái", meaning: "to come", partOfSpeech: "verb", exampleHanzi: "你来学校吗？", examplePinyin: "Nǐ lái xuéxiào ma?", exampleMeaning: "Are you coming to school?" },
  { id: 107, hanzi: "老师", pinyin: "lǎoshī", meaning: "teacher", partOfSpeech: "noun", exampleHanzi: "老师很好。", examplePinyin: "Lǎoshī hěn hǎo.", exampleMeaning: "The teacher is very good." },
  { id: 108, hanzi: "了", pinyin: "le", meaning: "indicates completed action", partOfSpeech: "particle", exampleHanzi: "我吃了饭。", examplePinyin: "Wǒ chī le fàn.", exampleMeaning: "I ate a meal." },
  { id: 109, hanzi: "冷", pinyin: "lěng", meaning: "cold", partOfSpeech: "adjective", exampleHanzi: "今天很冷。", examplePinyin: "Jīntiān hěn lěng.", exampleMeaning: "It is cold today." },
  { id: 110, hanzi: "里", pinyin: "lǐ", meaning: "inside", partOfSpeech: "noun", exampleHanzi: "书在包里。", examplePinyin: "Shū zài bāo lǐ.", exampleMeaning: "The book is in the bag." },
  { id: 111, hanzi: "两", pinyin: "liǎng", meaning: "two", partOfSpeech: "numeral", exampleHanzi: "我有两本书。", examplePinyin: "Wǒ yǒu liǎng běn shū.", exampleMeaning: "I have two books." },
  { id: 112, hanzi: "零", pinyin: "líng", meaning: "zero", partOfSpeech: "numeral", exampleHanzi: "现在是零点。", examplePinyin: "Xiànzài shì líng diǎn.", exampleMeaning: "It's zero o'clock." },
  { id: 113, hanzi: "六", pinyin: "liù", meaning: "six", partOfSpeech: "numeral", exampleHanzi: "我有六个朋友。", examplePinyin: "Wǒ yǒu liù gè péngyou.", exampleMeaning: "I have six friends." },
  { id: 114, hanzi: "吗", pinyin: "ma", meaning: "question particle", partOfSpeech: "particle", exampleHanzi: "你吃饭了吗？", examplePinyin: "Nǐ chī fàn le ma?", exampleMeaning: "Have you eaten?" },
  { id: 115, hanzi: "卖", pinyin: "mài", meaning: "to sell", partOfSpeech: "verb", exampleHanzi: "他卖书。", examplePinyin: "Tā mài shū.", exampleMeaning: "He sells books." },
  { id: 116, hanzi: "买", pinyin: "mǎi", meaning: "to buy", partOfSpeech: "verb", exampleHanzi: "我买苹果。", examplePinyin: "Wǒ mǎi píngguǒ.", exampleMeaning: "I buy apples." },
  { id: 117, hanzi: "妈妈", pinyin: "māma", meaning: "mom", partOfSpeech: "noun", exampleHanzi: "我妈妈在家。", examplePinyin: "Wǒ māma zài jiā.", exampleMeaning: "My mom is at home." },
  { id: 118, hanzi: "忙", pinyin: "máng", meaning: "busy", partOfSpeech: "adjective", exampleHanzi: "我很忙。", examplePinyin: "Wǒ hěn máng.", exampleMeaning: "I'm very busy." },
  { id: 119, hanzi: "猫", pinyin: "māo", meaning: "cat", partOfSpeech: "noun", exampleHanzi: "我有一只猫。", examplePinyin: "Wǒ yǒu yì zhī māo.", exampleMeaning: "I have a cat." },
  { id: 120, hanzi: "没关系", pinyin: "méi guānxi", meaning: "it doesn't matter", partOfSpeech: "fixed expression", exampleHanzi: "对不起。没关系。", examplePinyin: "Duìbuqǐ. Méi guānxi.", exampleMeaning: "Sorry. It's okay." },
  { id: 121, hanzi: "妹妹", pinyin: "mèimei", meaning: "younger sister", partOfSpeech: "noun", exampleHanzi: "我妹妹学习。", examplePinyin: "Wǒ mèimei xuéxí.", exampleMeaning: "My younger sister studies." },
  { id: 122, hanzi: "没事", pinyin: "méishì", meaning: "it's okay", partOfSpeech: "verb phrase", exampleHanzi: "没事。", examplePinyin: "Méishì.", exampleMeaning: "It's okay." },
  { id: 123, hanzi: "没有", pinyin: "méiyǒu", meaning: "not have", partOfSpeech: "verb", exampleHanzi: "我没有钱。", examplePinyin: "Wǒ méiyǒu qián.", exampleMeaning: "I don't have money." },
  { id: 124, hanzi: "们", pinyin: "men", meaning: "plural marker", partOfSpeech: "suffix", exampleHanzi: "我们是学生。", examplePinyin: "Wǒmen shì xuéshēng.", exampleMeaning: "We are students." },
  { id: 125, hanzi: "面包", pinyin: "miànbāo", meaning: "bread", partOfSpeech: "noun", exampleHanzi: "我吃面包。", examplePinyin: "Wǒ chī miànbāo.", exampleMeaning: "I eat bread." },
  { id: 126, hanzi: "面条儿", pinyin: "miàntiáor", meaning: "noodles", partOfSpeech: "noun", exampleHanzi: "我吃面条儿。", examplePinyin: "Wǒ chī miàntiáor.", exampleMeaning: "I eat noodles." },
  { id: 127, hanzi: "米饭", pinyin: "mǐfàn", meaning: "cooked rice", partOfSpeech: "noun", exampleHanzi: "我吃米饭。", examplePinyin: "Wǒ chī mǐfàn.", exampleMeaning: "I eat rice." },
  { id: 128, hanzi: "明年", pinyin: "míngnián", meaning: "next year", partOfSpeech: "noun", exampleHanzi: "明年我去中国。", examplePinyin: "Míngnián wǒ qù Zhōngguó.", exampleMeaning: "I will go to China next year." },
  { id: 129, hanzi: "明天", pinyin: "míngtiān", meaning: "tomorrow", partOfSpeech: "noun", exampleHanzi: "明天上课。", examplePinyin: "Míngtiān shàngkè.", exampleMeaning: "There is class tomorrow." },
  { id: 130, hanzi: "名字", pinyin: "míngzi", meaning: "name", partOfSpeech: "noun", exampleHanzi: "你的名字是什么？", examplePinyin: "Nǐ de míngzi shì shénme?", exampleMeaning: "What is your name?" },
  { id: 131, hanzi: "那", pinyin: "nà", meaning: "that", partOfSpeech: "pronoun", exampleHanzi: "那是我的书。", examplePinyin: "Nà shì wǒ de shū.", exampleMeaning: "That is my book." },
  { id: 132, hanzi: "哪", pinyin: "nǎ", meaning: "which", partOfSpeech: "pronoun", exampleHanzi: "你要哪本？", examplePinyin: "Nǐ yào nǎ běn?", exampleMeaning: "Which one do you want?" },
  { id: 133, hanzi: "那边", pinyin: "nàbiān", meaning: "over there", partOfSpeech: "pronoun", exampleHanzi: "他在那边。", examplePinyin: "Tā zài nàbiān.", exampleMeaning: "He is over there." },
  { id: 134, hanzi: "那个", pinyin: "nàge", meaning: "that one", partOfSpeech: "pronoun", exampleHanzi: "我买那个。", examplePinyin: "Wǒ mǎi nàge.", exampleMeaning: "I buy that one." },
  { id: 135, hanzi: "哪个", pinyin: "nǎge", meaning: "which one", partOfSpeech: "pronoun", exampleHanzi: "你要哪个？", examplePinyin: "Nǐ yào nǎge?", exampleMeaning: "Which one do you want?" },
  { id: 136, hanzi: "那里", pinyin: "nàlǐ", meaning: "there", partOfSpeech: "pronoun", exampleHanzi: "我住在那里。", examplePinyin: "Wǒ zhù zài nàlǐ.", exampleMeaning: "I live there." },
  { id: 137, hanzi: "哪里", pinyin: "nǎlǐ", meaning: "where", partOfSpeech: "pronoun", exampleHanzi: "你去哪里？", examplePinyin: "Nǐ qù nǎlǐ?", exampleMeaning: "Where are you going?" },
  { id: 138, hanzi: "男", pinyin: "nán", meaning: "male", partOfSpeech: "adjective", exampleHanzi: "他是男老师。", examplePinyin: "Tā shì nán lǎoshī.", exampleMeaning: "He is a male teacher." },
  { id: 139, hanzi: "男朋友", pinyin: "nánpéngyou", meaning: "boyfriend", partOfSpeech: "noun", exampleHanzi: "她有男朋友。", examplePinyin: "Tā yǒu nánpéngyou.", exampleMeaning: "She has a boyfriend." },
  { id: 140, hanzi: "那儿", pinyin: "nàr", meaning: "there", partOfSpeech: "pronoun", exampleHanzi: "他在那儿。", examplePinyin: "Tā zài nàr.", exampleMeaning: "He is there." },
  { id: 141, hanzi: "哪儿", pinyin: "nǎr", meaning: "where", partOfSpeech: "pronoun", exampleHanzi: "你住在哪儿？", examplePinyin: "Nǐ zhù zài nǎr?", exampleMeaning: "Where do you live?" },
  { id: 142, hanzi: "那些", pinyin: "nàxiē", meaning: "those", partOfSpeech: "pronoun", exampleHanzi: "我喜欢那些书。", examplePinyin: "Wǒ xǐhuan nàxiē shū.", exampleMeaning: "I like those books." },
  { id: 143, hanzi: "哪些", pinyin: "nǎxiē", meaning: "which ones", partOfSpeech: "pronoun", exampleHanzi: "你要哪些？", examplePinyin: "Nǐ yào nǎxiē?", exampleMeaning: "Which ones do you want?" },
  { id: 144, hanzi: "呢", pinyin: "ne", meaning: "question particle", partOfSpeech: "particle", exampleHanzi: "你呢？", examplePinyin: "Nǐ ne?", exampleMeaning: "How about you?" },
  { id: 145, hanzi: "能", pinyin: "néng", meaning: "can; be able to", partOfSpeech: "verb", exampleHanzi: "我能来。", examplePinyin: "Wǒ néng lái.", exampleMeaning: "I can come." },
  { id: 146, hanzi: "你", pinyin: "nǐ", meaning: "you", partOfSpeech: "pronoun", exampleHanzi: "你来了吗？", examplePinyin: "Nǐ lái le ma?", exampleMeaning: "Have you arrived?" },
  { id: 147, hanzi: "你好", pinyin: "nǐ hǎo", meaning: "hello", partOfSpeech: "fixed expression", exampleHanzi: "你好。", examplePinyin: "Nǐ hǎo.", exampleMeaning: "Hello." },
  { id: 148, hanzi: "年", pinyin: "nián", meaning: "year", partOfSpeech: "classifier", exampleHanzi: "我学汉语两年。", examplePinyin: "Wǒ xué Hànyǔ liǎng nián.", exampleMeaning: "I have studied Chinese for two years." },
  { id: 149, hanzi: "你们", pinyin: "nǐmen", meaning: "you (plural)", partOfSpeech: "pronoun", exampleHanzi: "你们去哪儿？", examplePinyin: "Nǐmen qù nǎr?", exampleMeaning: "Where are you going?" },
  { id: 150, hanzi: "您", pinyin: "nín", meaning: "you (polite)", partOfSpeech: "pronoun", exampleHanzi: "您好，老师。", examplePinyin: "Nín hǎo, lǎoshī.", exampleMeaning: "Hello, teacher." },
  { id: 151, hanzi: "牛奶", pinyin: "niúnǎi", meaning: "milk", partOfSpeech: "noun", exampleHanzi: "我喝牛奶。", examplePinyin: "Wǒ hē niúnǎi.", exampleMeaning: "I drink milk." },
  { id: 152, hanzi: "女", pinyin: "nǚ", meaning: "female", partOfSpeech: "adjective", exampleHanzi: "她是女老师。", examplePinyin: "Tā shì nǚ lǎoshī.", exampleMeaning: "She is a female teacher." },
  { id: 153, hanzi: "女儿", pinyin: "nǚ'ér", meaning: "daughter", partOfSpeech: "noun", exampleHanzi: "他有一个女儿。", examplePinyin: "Tā yǒu yí gè nǚ'ér.", exampleMeaning: "He has a daughter." },
  { id: 154, hanzi: "女朋友", pinyin: "nǚpéngyou", meaning: "girlfriend", partOfSpeech: "noun", exampleHanzi: "他有女朋友。", examplePinyin: "Tā yǒu nǚpéngyou.", exampleMeaning: "He has a girlfriend." },
  { id: 155, hanzi: "女士", pinyin: "nǚshì", meaning: "lady", partOfSpeech: "noun", exampleHanzi: "这位女士很好。", examplePinyin: "Zhè wèi nǚshì hěn hǎo.", exampleMeaning: "This lady is very kind." },
  { id: 156, hanzi: "朋友", pinyin: "péngyou", meaning: "friend", partOfSpeech: "noun", exampleHanzi: "他是我的朋友。", examplePinyin: "Tā shì wǒ de péngyou.", exampleMeaning: "He is my friend." },
  { id: 157, hanzi: "便宜", pinyin: "piányi", meaning: "cheap", partOfSpeech: "adjective", exampleHanzi: "这个很便宜。", examplePinyin: "Zhège hěn piányi.", exampleMeaning: "This is cheap." },
  { id: 158, hanzi: "漂亮", pinyin: "piàoliang", meaning: "beautiful", partOfSpeech: "adjective", exampleHanzi: "她很漂亮。", examplePinyin: "Tā hěn piàoliang.", exampleMeaning: "She is beautiful." },
  { id: 159, hanzi: "苹果", pinyin: "píngguǒ", meaning: "apple", partOfSpeech: "noun", exampleHanzi: "我吃苹果。", examplePinyin: "Wǒ chī píngguǒ.", exampleMeaning: "I eat apples." },
  { id: 160, hanzi: "七", pinyin: "qī", meaning: "seven", partOfSpeech: "numeral", exampleHanzi: "我有七本书。", examplePinyin: "Wǒ yǒu qī běn shū.", exampleMeaning: "I have seven books." },
  { id: 161, hanzi: "前", pinyin: "qián", meaning: "front; before", partOfSpeech: "noun", exampleHanzi: "他在我前边。", examplePinyin: "Tā zài wǒ qián biān.", exampleMeaning: "He is in front of me." },
  { id: 162, hanzi: "钱", pinyin: "qián", meaning: "money", partOfSpeech: "noun", exampleHanzi: "我有钱。", examplePinyin: "Wǒ yǒu qián.", exampleMeaning: "I have money." },
  { id: 163, hanzi: "千", pinyin: "qiān", meaning: "thousand", partOfSpeech: "numeral", exampleHanzi: "这本书一千元。", examplePinyin: "Zhè běn shū yì qiān yuán.", exampleMeaning: "This book costs one thousand yuan." },
  { id: 164, hanzi: "起床", pinyin: "qǐchuáng", meaning: "to get up", partOfSpeech: "verb", exampleHanzi: "我七点起床。", examplePinyin: "Wǒ qī diǎn qǐchuáng.", exampleMeaning: "I get up at seven." },
  { id: 165, hanzi: "请", pinyin: "qǐng", meaning: "please; to invite", partOfSpeech: "verb", exampleHanzi: "请坐。", examplePinyin: "Qǐng zuò.", exampleMeaning: "Please sit down." },
  { id: 166, hanzi: "请问", pinyin: "qǐngwèn", meaning: "may I ask", partOfSpeech: "verb", exampleHanzi: "请问，你叫什么名字？", examplePinyin: "Qǐngwèn, nǐ jiào shénme míngzi?", exampleMeaning: "May I ask, what is your name?" },
  { id: 167, hanzi: "去", pinyin: "qù", meaning: "to go", partOfSpeech: "verb", exampleHanzi: "我去学校。", examplePinyin: "Wǒ qù xuéxiào.", exampleMeaning: "I go to school." },
  { id: 168, hanzi: "去年", pinyin: "qùnián", meaning: "last year", partOfSpeech: "noun", exampleHanzi: "去年我学汉语。", examplePinyin: "Qùnián wǒ xué Hànyǔ.", exampleMeaning: "Last year I studied Chinese." },
  { id: 169, hanzi: "热", pinyin: "rè", meaning: "hot", partOfSpeech: "adjective", exampleHanzi: "今天很热。", examplePinyin: "Jīntiān hěn rè.", exampleMeaning: "It is hot today." },
  { id: 170, hanzi: "人", pinyin: "rén", meaning: "person", partOfSpeech: "noun", exampleHanzi: "这个人很好。", examplePinyin: "Zhège rén hěn hǎo.", exampleMeaning: "This person is very nice." },
  { id: 171, hanzi: "认识", pinyin: "rènshi", meaning: "to know; to recognize", partOfSpeech: "verb", exampleHanzi: "我认识他。", examplePinyin: "Wǒ rènshi tā.", exampleMeaning: "I know him." },
  { id: 172, hanzi: "日", pinyin: "rì", meaning: "day", partOfSpeech: "classifier", exampleHanzi: "三日见。", examplePinyin: "Sān rì jiàn.", exampleMeaning: "See you on the third." },
  { id: 173, hanzi: "三", pinyin: "sān", meaning: "three", partOfSpeech: "numeral", exampleHanzi: "我有三个学生。", examplePinyin: "Wǒ yǒu sān gè xuéshēng.", exampleMeaning: "I have three students." },
  { id: 174, hanzi: "上", pinyin: "shàng", meaning: "up; to attend", partOfSpeech: "verb", exampleHanzi: "我上课。", examplePinyin: "Wǒ shàng kè.", exampleMeaning: "I attend class." },
  { id: 175, hanzi: "上班", pinyin: "shàngbān", meaning: "to go to work", partOfSpeech: "verb", exampleHanzi: "我八点上班。", examplePinyin: "Wǒ bā diǎn shàngbān.", exampleMeaning: "I go to work at eight." },
  { id: 176, hanzi: "商店", pinyin: "shāngdiàn", meaning: "store", partOfSpeech: "noun", exampleHanzi: "我去商店买东西。", examplePinyin: "Wǒ qù shāngdiàn mǎi dōngxi.", exampleMeaning: "I go to the store to buy things." },
  { id: 177, hanzi: "上课", pinyin: "shàngkè", meaning: "to attend class", partOfSpeech: "verb", exampleHanzi: "我们上课。", examplePinyin: "Wǒmen shàngkè.", exampleMeaning: "We have class." },
  { id: 178, hanzi: "上午", pinyin: "shàngwǔ", meaning: "morning (before noon)", partOfSpeech: "noun", exampleHanzi: "上午我上课。", examplePinyin: "Shàngwǔ wǒ shàngkè.", exampleMeaning: "I have class in the morning." },
  { id: 179, hanzi: "上学", pinyin: "shàngxué", meaning: "to go to school", partOfSpeech: "verb", exampleHanzi: "孩子上学。", examplePinyin: "Háizi shàngxué.", exampleMeaning: "The child goes to school." },
  { id: 180, hanzi: "少", pinyin: "shǎo", meaning: "few; little", partOfSpeech: "adjective", exampleHanzi: "人很少。", examplePinyin: "Rén hěn shǎo.", exampleMeaning: "There are few people." },
  { id: 181, hanzi: "谁", pinyin: "shéi", meaning: "who", partOfSpeech: "pronoun", exampleHanzi: "谁是老师？", examplePinyin: "Shéi shì lǎoshī?", exampleMeaning: "Who is the teacher?" },
  { id: 182, hanzi: "生病", pinyin: "shēngbìng", meaning: "to get sick", partOfSpeech: "verb", exampleHanzi: "他生病了。", examplePinyin: "Tā shēngbìng le.", exampleMeaning: "He got sick." },
  { id: 183, hanzi: "什么", pinyin: "shénme", meaning: "what", partOfSpeech: "pronoun", exampleHanzi: "你要什么？", examplePinyin: "Nǐ yào shénme?", exampleMeaning: "What do you want?" },
  { id: 184, hanzi: "十", pinyin: "shí", meaning: "ten", partOfSpeech: "numeral", exampleHanzi: "我有十本书。", examplePinyin: "Wǒ yǒu shí běn shū.", exampleMeaning: "I have ten books." },
  { id: 185, hanzi: "事", pinyin: "shì", meaning: "matter; thing", partOfSpeech: "noun", exampleHanzi: "这是一件事。", examplePinyin: "Zhè shì yí jiàn shì.", exampleMeaning: "This is a matter." },
  { id: 186, hanzi: "是", pinyin: "shì", meaning: "to be", partOfSpeech: "verb", exampleHanzi: "他是学生。", examplePinyin: "Tā shì xuéshēng.", exampleMeaning: "He is a student." },
  { id: 187, hanzi: "时候", pinyin: "shíhou", meaning: "time; moment", partOfSpeech: "noun", exampleHanzi: "吃饭的时候。", examplePinyin: "Chī fàn de shíhou.", exampleMeaning: "Mealtime." },
  { id: 188, hanzi: "时间", pinyin: "shíjiān", meaning: "time", partOfSpeech: "noun", exampleHanzi: "我没有时间。", examplePinyin: "Wǒ méiyǒu shíjiān.", exampleMeaning: "I don't have time." },
  { id: 189, hanzi: "手机", pinyin: "shǒujī", meaning: "mobile phone", partOfSpeech: "noun", exampleHanzi: "我的手机在这儿。", examplePinyin: "Wǒ de shǒujī zài zhèr.", exampleMeaning: "My phone is here." },
  { id: 190, hanzi: "书", pinyin: "shū", meaning: "book", partOfSpeech: "noun", exampleHanzi: "我看书。", examplePinyin: "Wǒ kàn shū.", exampleMeaning: "I read a book." },
  { id: 191, hanzi: "书店", pinyin: "shūdiàn", meaning: "bookstore", partOfSpeech: "noun", exampleHanzi: "我去书店。", examplePinyin: "Wǒ qù shūdiàn.", exampleMeaning: "I go to the bookstore." },
  { id: 192, hanzi: "睡", pinyin: "shuì", meaning: "to sleep", partOfSpeech: "verb", exampleHanzi: "我睡了。", examplePinyin: "Wǒ shuì le.", exampleMeaning: "I slept." },
  { id: 193, hanzi: "水", pinyin: "shuǐ", meaning: "water", partOfSpeech: "noun", exampleHanzi: "我喝水。", examplePinyin: "Wǒ hē shuǐ.", exampleMeaning: "I drink water." },
  { id: 194, hanzi: "水果", pinyin: "shuǐguǒ", meaning: "fruit", partOfSpeech: "noun", exampleHanzi: "我吃水果。", examplePinyin: "Wǒ chī shuǐguǒ.", exampleMeaning: "I eat fruit." },
  { id: 195, hanzi: "睡觉", pinyin: "shuìjiào", meaning: "to sleep", partOfSpeech: "verb", exampleHanzi: "我想睡觉。", examplePinyin: "Wǒ xiǎng shuìjiào.", exampleMeaning: "I want to sleep." },
  { id: 196, hanzi: "说", pinyin: "shuō", meaning: "to say; to speak", partOfSpeech: "verb", exampleHanzi: "他说汉语。", examplePinyin: "Tā shuō Hànyǔ.", exampleMeaning: "He speaks Chinese." },
  { id: 197, hanzi: "说话", pinyin: "shuōhuà", meaning: "to talk", partOfSpeech: "verb", exampleHanzi: "不要说话。", examplePinyin: "Bú yào shuōhuà.", exampleMeaning: "Don't talk." },
  { id: 198, hanzi: "四", pinyin: "sì", meaning: "four", partOfSpeech: "numeral", exampleHanzi: "我有四个朋友。", examplePinyin: "Wǒ yǒu sì gè péngyou.", exampleMeaning: "I have four friends." },
  { id: 199, hanzi: "岁", pinyin: "suì", meaning: "years old", partOfSpeech: "classifier", exampleHanzi: "我二十岁。", examplePinyin: "Wǒ èrshí suì.", exampleMeaning: "I am twenty years old." },
  { id: 200, hanzi: "他", pinyin: "tā", meaning: "he", partOfSpeech: "pronoun", exampleHanzi: "他是老师。", examplePinyin: "Tā shì lǎoshī.", exampleMeaning: "He is a teacher." },
  { id: 201, hanzi: "它", pinyin: "tā", meaning: "it", partOfSpeech: "pronoun", exampleHanzi: "它在桌子上。", examplePinyin: "Tā zài zhuōzi shàng.", exampleMeaning: "It is on the table." },
  { id: 202, hanzi: "她", pinyin: "tā", meaning: "she", partOfSpeech: "pronoun", exampleHanzi: "她是学生。", examplePinyin: "Tā shì xuéshēng.", exampleMeaning: "She is a student." },
  { id: 203, hanzi: "太", pinyin: "tài", meaning: "too; very", partOfSpeech: "adverb", exampleHanzi: "这本书太贵了。", examplePinyin: "Zhè běn shū tài guì le.", exampleMeaning: "This book is too expensive." },
  { id: 204, hanzi: "他们", pinyin: "tāmen", meaning: "they (male/mixed)", partOfSpeech: "pronoun", exampleHanzi: "他们是朋友。", examplePinyin: "Tāmen shì péngyou.", exampleMeaning: "They are friends." },
  { id: 205, hanzi: "它们", pinyin: "tāmen", meaning: "they (things)", partOfSpeech: "pronoun", exampleHanzi: "它们在这儿。", examplePinyin: "Tāmen zài zhèr.", exampleMeaning: "They are here." },
  { id: 206, hanzi: "她们", pinyin: "tāmen", meaning: "they (female)", partOfSpeech: "pronoun", exampleHanzi: "她们在上课。", examplePinyin: "Tāmen zài shàngkè.", exampleMeaning: "They are having class." },
  { id: 207, hanzi: "天", pinyin: "tiān", meaning: "day", partOfSpeech: "classifier", exampleHanzi: "今天是第一天。", examplePinyin: "Jīntiān shì dì yī tiān.", exampleMeaning: "Today is the first day." },
  { id: 208, hanzi: "天气", pinyin: "tiānqì", meaning: "weather", partOfSpeech: "noun", exampleHanzi: "今天的天气很好。", examplePinyin: "Jīntiān de tiānqì hěn hǎo.", exampleMeaning: "The weather today is very good." },
  { id: 209, hanzi: "听", pinyin: "tīng", meaning: "to listen", partOfSpeech: "verb", exampleHanzi: "我听音乐。", examplePinyin: "Wǒ tīng yīnyuè.", exampleMeaning: "I listen to music." },
  { id: 210, hanzi: "听见", pinyin: "tīngjiàn", meaning: "to hear", partOfSpeech: "verb", exampleHanzi: "我听见老师说话了。", examplePinyin: "Wǒ tīngjiàn lǎoshī shuōhuà le.", exampleMeaning: "I heard the teacher speak." },
  { id: 211, hanzi: "同学", pinyin: "tóngxué", meaning: "classmate", partOfSpeech: "noun", exampleHanzi: "他是我的同学。", examplePinyin: "Tā shì wǒ de tóngxué.", exampleMeaning: "He is my classmate." },
  { id: 212, hanzi: "外", pinyin: "wài", meaning: "outside", partOfSpeech: "noun", exampleHanzi: "他在外边。", examplePinyin: "Tā zài wài biān.", exampleMeaning: "He is outside." },
  { id: 213, hanzi: "外边", pinyin: "wàibian", meaning: "outside", partOfSpeech: "noun", exampleHanzi: "孩子在外边玩。", examplePinyin: "Háizi zài wàibian wán.", exampleMeaning: "The child is playing outside." },
  { id: 214, hanzi: "玩", pinyin: "wán", meaning: "to play", partOfSpeech: "verb", exampleHanzi: "我们一起玩。", examplePinyin: "Wǒmen yìqǐ wán.", exampleMeaning: "We play together." },
  { id: 215, hanzi: "晚", pinyin: "wǎn", meaning: "late", partOfSpeech: "adjective", exampleHanzi: "今天很晚。", examplePinyin: "Jīntiān hěn wǎn.", exampleMeaning: "It is late today." },
  { id: 216, hanzi: "晚饭", pinyin: "wǎnfàn", meaning: "dinner", partOfSpeech: "noun", exampleHanzi: "我吃晚饭。", examplePinyin: "Wǒ chī wǎnfàn.", exampleMeaning: "I eat dinner." },
  { id: 217, hanzi: "晚上", pinyin: "wǎnshang", meaning: "evening", partOfSpeech: "noun", exampleHanzi: "晚上我在家。", examplePinyin: "Wǎnshang wǒ zài jiā.", exampleMeaning: "I am at home in the evening." },
  { id: 218, hanzi: "喂", pinyin: "wèi", meaning: "hello (on the phone)", partOfSpeech: "interjection", exampleHanzi: "喂，你吃什么？", examplePinyin: "Wèi, nǐ chī shénme?", exampleMeaning: "Hello, what are you eating?" },
  { id: 219, hanzi: "问", pinyin: "wèn", meaning: "to ask", partOfSpeech: "verb", exampleHanzi: "我问老师。", examplePinyin: "Wǒ wèn lǎoshī.", exampleMeaning: "I ask the teacher." },
  { id: 220, hanzi: "问题", pinyin: "wèntí", meaning: "question; problem", partOfSpeech: "noun", exampleHanzi: "这个问题很简单。", examplePinyin: "Zhège wèntí hěn jiǎndān.", exampleMeaning: "This question is very simple." },
  { id: 221, hanzi: "我", pinyin: "wǒ", meaning: "I", partOfSpeech: "pronoun", exampleHanzi: "我是学生。", examplePinyin: "Wǒ shì xuéshēng.", exampleMeaning: "I am a student." },
  { id: 222, hanzi: "我们", pinyin: "wǒmen", meaning: "we", partOfSpeech: "pronoun", exampleHanzi: "我们去上课。", examplePinyin: "Wǒmen qù shàngkè.", exampleMeaning: "We go to class." },
  { id: 223, hanzi: "五", pinyin: "wǔ", meaning: "five", partOfSpeech: "numeral", exampleHanzi: "我有五本书。", examplePinyin: "Wǒ yǒu wǔ běn shū.", exampleMeaning: "I have five books." },
  { id: 224, hanzi: "午饭", pinyin: "wǔfàn", meaning: "lunch", partOfSpeech: "noun", exampleHanzi: "我吃午饭。", examplePinyin: "Wǒ chī wǔfàn.", exampleMeaning: "I eat lunch." },
  { id: 225, hanzi: "下", pinyin: "xià", meaning: "down; to get off", partOfSpeech: "verb", exampleHanzi: "我下车。", examplePinyin: "Wǒ xià chē.", exampleMeaning: "I get off the bus." },
  { id: 226, hanzi: "下雨", pinyin: "xià yǔ", meaning: "to rain", partOfSpeech: "fixed expression", exampleHanzi: "今天下雨了。", examplePinyin: "Jīntiān xià yǔ le.", exampleMeaning: "It is raining today." },
  { id: 227, hanzi: "下班", pinyin: "xiàbān", meaning: "to get off work", partOfSpeech: "verb", exampleHanzi: "我六点下班。", examplePinyin: "Wǒ liù diǎn xiàbān.", exampleMeaning: "I get off work at six." },
  { id: 228, hanzi: "下课", pinyin: "xiàkè", meaning: "class is over", partOfSpeech: "verb", exampleHanzi: "现在下课了。", examplePinyin: "Xiànzài xiàkè le.", exampleMeaning: "Class is over now." },
  { id: 229, hanzi: "想", pinyin: "xiǎng", meaning: "to want; to think", partOfSpeech: "verb", exampleHanzi: "我想喝水。", examplePinyin: "Wǒ xiǎng hē shuǐ.", exampleMeaning: "I want to drink water." },
  { id: 230, hanzi: "先生", pinyin: "xiānsheng", meaning: "Mr.; gentleman", partOfSpeech: "noun", exampleHanzi: "王先生很好。", examplePinyin: "Wáng xiānsheng hěn hǎo.", exampleMeaning: "Mr. Wang is very nice." },
  { id: 231, hanzi: "现在", pinyin: "xiànzài", meaning: "now", partOfSpeech: "noun", exampleHanzi: "现在几点？", examplePinyin: "Xiànzài jǐ diǎn?", exampleMeaning: "What time is it now?" },
  { id: 232, hanzi: "小", pinyin: "xiǎo", meaning: "small", partOfSpeech: "adjective", exampleHanzi: "这只猫很小。", examplePinyin: "Zhè zhī māo hěn xiǎo.", exampleMeaning: "This cat is very small." },
  { id: 233, hanzi: "小朋友", pinyin: "xiǎopéngyou", meaning: "child", partOfSpeech: "noun", exampleHanzi: "这个小朋友很可爱。", examplePinyin: "Zhège xiǎopéngyou hěn kě'ài.", exampleMeaning: "This child is very cute." },
  { id: 234, hanzi: "小时", pinyin: "xiǎoshí", meaning: "hour", partOfSpeech: "noun", exampleHanzi: "我学了一小时。", examplePinyin: "Wǒ xué le yì xiǎoshí.", exampleMeaning: "I studied for one hour." },
  { id: 235, hanzi: "小学", pinyin: "xiǎoxué", meaning: "primary school", partOfSpeech: "noun", exampleHanzi: "他在小学学习。", examplePinyin: "Tā zài xiǎoxué xuéxí.", exampleMeaning: "He studies at a primary school." },
  { id: 236, hanzi: "小学生", pinyin: "xiǎoxuéshēng", meaning: "primary school student", partOfSpeech: "noun", exampleHanzi: "她是小学生。", examplePinyin: "Tā shì xiǎoxuéshēng.", exampleMeaning: "She is a primary school student." },
  { id: 237, hanzi: "下午", pinyin: "xiàwǔ", meaning: "afternoon", partOfSpeech: "noun", exampleHanzi: "下午我上班。", examplePinyin: "Xiàwǔ wǒ shàngbān.", exampleMeaning: "I work in the afternoon." },
  { id: 238, hanzi: "写", pinyin: "xiě", meaning: "to write", partOfSpeech: "verb", exampleHanzi: "我写汉字。", examplePinyin: "Wǒ xiě Hànzì.", exampleMeaning: "I write Chinese characters." },
  { id: 239, hanzi: "些", pinyin: "xiē", meaning: "some", partOfSpeech: "classifier", exampleHanzi: "一些书。", examplePinyin: "Yìxiē shū.", exampleMeaning: "Some books." },
  { id: 240, hanzi: "谢谢", pinyin: "xièxie", meaning: "thank", partOfSpeech: "verb", exampleHanzi: "谢谢你。", examplePinyin: "Xièxie nǐ.", exampleMeaning: "Thank you." },
  { id: 241, hanzi: "喜欢", pinyin: "xǐhuan", meaning: "to like", partOfSpeech: "verb", exampleHanzi: "我喜欢汉语。", examplePinyin: "Wǒ xǐhuan Hànyǔ.", exampleMeaning: "I like Chinese." },
  { id: 242, hanzi: "新", pinyin: "xīn", meaning: "new", partOfSpeech: "adjective", exampleHanzi: "这是新书。", examplePinyin: "Zhè shì xīn shū.", exampleMeaning: "This is a new book." },
  { id: 243, hanzi: "星期", pinyin: "xīngqī", meaning: "week", partOfSpeech: "noun", exampleHanzi: "这个星期很忙。", examplePinyin: "Zhège xīngqī hěn máng.", exampleMeaning: "This week is very busy." },
  { id: 244, hanzi: "星期日", pinyin: "xīngqīrì", meaning: "Sunday", partOfSpeech: "noun", exampleHanzi: "星期日我休息。", examplePinyin: "Xīngqīrì wǒ xiūxi.", exampleMeaning: "I rest on Sunday." },
  { id: 245, hanzi: "星期天", pinyin: "xīngqītiān", meaning: "Sunday", partOfSpeech: "noun", exampleHanzi: "星期天见。", examplePinyin: "Xīngqītiān jiàn.", exampleMeaning: "See you on Sunday." },
  { id: 246, hanzi: "休息", pinyin: "xiūxi", meaning: "to rest", partOfSpeech: "verb", exampleHanzi: "我想休息。", examplePinyin: "Wǒ xiǎng xiūxi.", exampleMeaning: "I want to rest." },
  { id: 247, hanzi: "学", pinyin: "xué", meaning: "to study", partOfSpeech: "verb", exampleHanzi: "我学汉语。", examplePinyin: "Wǒ xué Hànyǔ.", exampleMeaning: "I study Chinese." },
  { id: 248, hanzi: "雪", pinyin: "xuě", meaning: "snow", partOfSpeech: "noun", exampleHanzi: "下雪了。", examplePinyin: "Xià xuě le.", exampleMeaning: "It is snowing." },
  { id: 249, hanzi: "学生", pinyin: "xuéshēng", meaning: "student", partOfSpeech: "noun", exampleHanzi: "我是学生。", examplePinyin: "Wǒ shì xuéshēng.", exampleMeaning: "I am a student." },
  { id: 250, hanzi: "学习", pinyin: "xuéxí", meaning: "to study; to learn", partOfSpeech: "verb", exampleHanzi: "我学习汉语。", examplePinyin: "Wǒ xuéxí Hànyǔ.", exampleMeaning: "I study Chinese." },
  { id: 251, hanzi: "学校", pinyin: "xuéxiào", meaning: "school", partOfSpeech: "noun", exampleHanzi: "我在学校学习。", examplePinyin: "Wǒ zài xuéxiào xuéxí.", exampleMeaning: "I study at school." },
  { id: 252, hanzi: "要", pinyin: "yào", meaning: "to want", partOfSpeech: "verb", exampleHanzi: "我要喝水。", examplePinyin: "Wǒ yào hē shuǐ.", exampleMeaning: "I want to drink water." },
  { id: 253, hanzi: "也", pinyin: "yě", meaning: "also", partOfSpeech: "adverb", exampleHanzi: "我也去。", examplePinyin: "Wǒ yě qù.", exampleMeaning: "I go too." },
  { id: 254, hanzi: "一", pinyin: "yī", meaning: "one", partOfSpeech: "numeral", exampleHanzi: "我有一本书。", examplePinyin: "Wǒ yǒu yī běn shū.", exampleMeaning: "I have one book." },
  { id: 255, hanzi: "一半", pinyin: "yíbàn", meaning: "half", partOfSpeech: "numeral", exampleHanzi: "我吃了一半。", examplePinyin: "Wǒ chī le yíbàn.", exampleMeaning: "I ate half." },
  { id: 256, hanzi: "一点儿", pinyin: "yìdiǎnr", meaning: "a little", partOfSpeech: "quantifier", exampleHanzi: "我喝一点儿水。", examplePinyin: "Wǒ hē yìdiǎnr shuǐ.", exampleMeaning: "I drink a little water." },
  { id: 257, hanzi: "衣服", pinyin: "yīfu", meaning: "clothes", partOfSpeech: "noun", exampleHanzi: "我买了衣服。", examplePinyin: "Wǒ mǎi le yīfu.", exampleMeaning: "I bought clothes." },
  { id: 258, hanzi: "医生", pinyin: "yīshēng", meaning: "doctor", partOfSpeech: "noun", exampleHanzi: "他是医生。", examplePinyin: "Tā shì yīshēng.", exampleMeaning: "He is a doctor." },
  { id: 259, hanzi: "一下", pinyin: "yíxià", meaning: "a bit; briefly", partOfSpeech: "adverb", exampleHanzi: "你等一下。", examplePinyin: "Nǐ děng yíxià.", exampleMeaning: "Wait a moment." },
  { id: 260, hanzi: "一些", pinyin: "yìxiē", meaning: "some", partOfSpeech: "quantifier", exampleHanzi: "我买了一些水果。", examplePinyin: "Wǒ mǎi le yìxiē shuǐguǒ.", exampleMeaning: "I bought some fruit." },
  { id: 261, hanzi: "医院", pinyin: "yīyuàn", meaning: "hospital", partOfSpeech: "noun", exampleHanzi: "他在医院。", examplePinyin: "Tā zài yīyuàn.", exampleMeaning: "He is in the hospital." },
  { id: 262, hanzi: "椅子", pinyin: "yǐzi", meaning: "chair", partOfSpeech: "noun", exampleHanzi: "我坐在椅子上。", examplePinyin: "Wǒ zuò zài yǐzi shàng.", exampleMeaning: "I sit on the chair." },
  { id: 263, hanzi: "有", pinyin: "yǒu", meaning: "to have", partOfSpeech: "verb", exampleHanzi: "我有时间。", examplePinyin: "Wǒ yǒu shíjiān.", exampleMeaning: "I have time." },
  { id: 264, hanzi: "有的", pinyin: "yǒude", meaning: "some", partOfSpeech: "pronoun", exampleHanzi: "有的学生在学习。", examplePinyin: "Yǒude xuéshēng zài xuéxí.", exampleMeaning: "Some students are studying." },
  { id: 265, hanzi: "有些", pinyin: "yǒuxiē", meaning: "some; a bit", partOfSpeech: "pronoun", exampleHanzi: "我有些累。", examplePinyin: "Wǒ yǒuxiē lèi.", exampleMeaning: "I'm a bit tired." },
  { id: 266, hanzi: "有一点儿", pinyin: "yǒu yìdiǎnr", meaning: "a little", partOfSpeech: "adverb", exampleHanzi: "今天有点儿冷。", examplePinyin: "Jīntiān yǒudiǎnr lěng.", exampleMeaning: "It's a little cold today." },
  { id: 267, hanzi: "雨", pinyin: "yǔ", meaning: "rain", partOfSpeech: "noun", exampleHanzi: "外边有雨。", examplePinyin: "Wàibian yǒu yǔ.", exampleMeaning: "There is rain outside." },
  { id: 268, hanzi: "元", pinyin: "yuán", meaning: "yuan (currency)", partOfSpeech: "classifier", exampleHanzi: "十元。", examplePinyin: "Shí yuán.", exampleMeaning: "Ten yuan." },
  { id: 269, hanzi: "月", pinyin: "yuè", meaning: "month", partOfSpeech: "classifier", exampleHanzi: "这个月很忙。", examplePinyin: "Zhège yuè hěn máng.", exampleMeaning: "This month is very busy." },
  { id: 270, hanzi: "再", pinyin: "zài", meaning: "again", partOfSpeech: "adverb", exampleHanzi: "请再说一次。", examplePinyin: "Qǐng zài shuō yí cì.", exampleMeaning: "Please say it again." },
  { id: 271, hanzi: "在", pinyin: "zài", meaning: "to be at", partOfSpeech: "verb", exampleHanzi: "我在家。", examplePinyin: "Wǒ zài jiā.", exampleMeaning: "I am at home." },
  { id: 272, hanzi: "再见", pinyin: "zàijiàn", meaning: "goodbye", partOfSpeech: "verb", exampleHanzi: "再见。", examplePinyin: "Zàijiàn.", exampleMeaning: "Goodbye." },
  { id: 273, hanzi: "早", pinyin: "zǎo", meaning: "early", partOfSpeech: "adjective", exampleHanzi: "今天很早。", examplePinyin: "Jīntiān hěn zǎo.", exampleMeaning: "It's early today." },
  { id: 274, hanzi: "早饭", pinyin: "zǎofàn", meaning: "breakfast", partOfSpeech: "noun", exampleHanzi: "我吃早饭。", examplePinyin: "Wǒ chī zǎofàn.", exampleMeaning: "I eat breakfast." },
  { id: 275, hanzi: "早上", pinyin: "zǎoshang", meaning: "morning", partOfSpeech: "noun", exampleHanzi: "早上我上课。", examplePinyin: "Zǎoshang wǒ shàngkè.", exampleMeaning: "I have class in the morning." },
  { id: 276, hanzi: "怎么", pinyin: "zěnme", meaning: "how", partOfSpeech: "pronoun", exampleHanzi: "你怎么来？", examplePinyin: "Nǐ zěnme lái?", exampleMeaning: "How did you come?" },
  { id: 277, hanzi: "怎么样", pinyin: "zěnmeyàng", meaning: "how about; how is", partOfSpeech: "pronoun", exampleHanzi: "这个菜怎么样？", examplePinyin: "Zhège cài zěnmeyàng?", exampleMeaning: "How is this dish?" },
  { id: 278, hanzi: "找", pinyin: "zhǎo", meaning: "to look for", partOfSpeech: "verb", exampleHanzi: "我找老师。", examplePinyin: "Wǒ zhǎo lǎoshī.", exampleMeaning: "I'm looking for the teacher." },
  { id: 279, hanzi: "这", pinyin: "zhè", meaning: "this", partOfSpeech: "pronoun", exampleHanzi: "这是我的书。", examplePinyin: "Zhè shì wǒ de shū.", exampleMeaning: "This is my book." },
  { id: 280, hanzi: "这边", pinyin: "zhèbiān", meaning: "here", partOfSpeech: "pronoun", exampleHanzi: "我在这边。", examplePinyin: "Wǒ zài zhèbiān.", exampleMeaning: "I'm here." },
  { id: 281, hanzi: "这个", pinyin: "zhège", meaning: "this one", partOfSpeech: "pronoun", exampleHanzi: "我买这个。", examplePinyin: "Wǒ mǎi zhège.", exampleMeaning: "I buy this one." },
  { id: 282, hanzi: "这里", pinyin: "zhèlǐ", meaning: "here", partOfSpeech: "pronoun", exampleHanzi: "我住在这里。", examplePinyin: "Wǒ zhù zài zhèlǐ.", exampleMeaning: "I live here." },
  { id: 283, hanzi: "真", pinyin: "zhēn", meaning: "really", partOfSpeech: "adverb", exampleHanzi: "真好。", examplePinyin: "Zhēn hǎo.", exampleMeaning: "Really good." },
  { id: 284, hanzi: "正在", pinyin: "zhèngzài", meaning: "in the process of", partOfSpeech: "adverb", exampleHanzi: "我正在学习。", examplePinyin: "Wǒ zhèngzài xuéxí.", exampleMeaning: "I am studying." },
  { id: 285, hanzi: "这儿", pinyin: "zhèr", meaning: "here", partOfSpeech: "pronoun", exampleHanzi: "我在这儿。", examplePinyin: "Wǒ zài zhèr.", exampleMeaning: "I'm here." },
  { id: 286, hanzi: "这些", pinyin: "zhèxiē", meaning: "these", partOfSpeech: "pronoun", exampleHanzi: "我喜欢这些书。", examplePinyin: "Wǒ xǐhuan zhèxiē shū.", exampleMeaning: "I like these books." },
  { id: 287, hanzi: "只", pinyin: "zhī", meaning: "measure word (animals)", partOfSpeech: "classifier", exampleHanzi: "一只猫。", examplePinyin: "Yì zhī māo.", exampleMeaning: "One cat." },
  { id: 288, hanzi: "知道", pinyin: "zhīdào", meaning: "to know", partOfSpeech: "verb", exampleHanzi: "我知道了。", examplePinyin: "Wǒ zhīdào le.", exampleMeaning: "I know." },
  { id: 289, hanzi: "中国", pinyin: "Zhōngguó", meaning: "China", partOfSpeech: "noun", exampleHanzi: "我去中国。", examplePinyin: "Wǒ qù Zhōngguó.", exampleMeaning: "I go to China." },
  { id: 290, hanzi: "中文", pinyin: "Zhōngwén", meaning: "Chinese (language)", partOfSpeech: "noun", exampleHanzi: "我学中文。", examplePinyin: "Wǒ xué Zhōngwén.", exampleMeaning: "I study Chinese." },
  { id: 291, hanzi: "中午", pinyin: "zhōngwǔ", meaning: "noon", partOfSpeech: "noun", exampleHanzi: "中午见。", examplePinyin: "Zhōngwǔ jiàn.", exampleMeaning: "See you at noon." },
  { id: 292, hanzi: "中学", pinyin: "zhōngxué", meaning: "middle school", partOfSpeech: "noun", exampleHanzi: "他在中学学习。", examplePinyin: "Tā zài zhōngxué xuéxí.", exampleMeaning: "He studies at a middle school." },
  { id: 293, hanzi: "中学生", pinyin: "zhōngxuéshēng", meaning: "middle school student", partOfSpeech: "noun", exampleHanzi: "她是中学生。", examplePinyin: "Tā shì zhōngxuéshēng.", exampleMeaning: "She is a middle school student." },
  { id: 294, hanzi: "住", pinyin: "zhù", meaning: "to live", partOfSpeech: "verb", exampleHanzi: "我住在北京。", examplePinyin: "Wǒ zhù zài Běijīng.", exampleMeaning: "I live in Beijing." },
  { id: 295, hanzi: "桌子", pinyin: "zhuōzi", meaning: "table", partOfSpeech: "noun", exampleHanzi: "书在桌子上。", examplePinyin: "Shū zài zhuōzi shàng.", exampleMeaning: "The book is on the table." },
  { id: 296, hanzi: "字", pinyin: "zì", meaning: "character", partOfSpeech: "noun", exampleHanzi: "这个字很难。", examplePinyin: "Zhège zì hěn nán.", exampleMeaning: "This character is difficult." },
  { id: 297, hanzi: "坐", pinyin: "zuò", meaning: "to sit", partOfSpeech: "verb", exampleHanzi: "请坐。", examplePinyin: "Qǐng zuò.", exampleMeaning: "Please sit." },
  { id: 298, hanzi: "做", pinyin: "zuò", meaning: "to do", partOfSpeech: "verb", exampleHanzi: "我做作业。", examplePinyin: "Wǒ zuò zuòyè.", exampleMeaning: "I do homework." },
  { id: 299, hanzi: "做饭", pinyin: "zuò fàn", meaning: "to cook", partOfSpeech: "fixed expression", exampleHanzi: "我在做饭。", examplePinyin: "Wǒ zài zuò fàn.", exampleMeaning: "I am cooking." },
  { id: 300, hanzi: "昨天", pinyin: "zuótiān", meaning: "yesterday", partOfSpeech: "noun", exampleHanzi: "昨天我上班。", examplePinyin: "Zuótiān wǒ shàngbān.", exampleMeaning: "I worked yesterday." },
];

export const partsOfSpeech: PartOfSpeech[] = [
  "verb", "noun", "adjective", "adverb", "pronoun", "numeral",
  "classifier", "particle", "conjunction", "preposition",
  "interjection", "prefix", "suffix", "fixed expression",
  "verb phrase", "quantifier", "other",
];
